//betted amout? elr nåt sätt att hantera hur mycket ligger på bordet
var tableSpots = [
  {
    username: undefined,
    chips: undefined,
    gameStatus: undefined,
    role: undefined,
    hand: [],
    bettedAmount: 0,
    card1posX: 150,
    card1posY: 155,
    card2posX: 185,
    card2posY: 155,
  },
  {
    username: undefined,
    chips: undefined,
    gameStatus: undefined,
    role: undefined,
    hand: [],
    bettedAmount: 0,
    card1posX: 150,
    card1posY: 300,
    card2posX: 185,
    card2posY: 300,
  },
  {
    username: undefined,
    chips: undefined,
    gameStatus: undefined,
    role: undefined,
    hand: [],
    bettedAmount: 0,
    card1posX: 570,
    card1posY: 155,
    card2posX: 605,
    card2posY: 155,
  },
  {
    username: undefined,
    chips: undefined,
    gameStatus: undefined,
    role: undefined,
    hand: [],
    bettedAmount: 0,
    card1posX: 570,
    card1posY: 300,
    card2posX: 605,
    card2posY: 300,
  },
  {
    username: undefined,
    chips: undefined,
    gameStatus: undefined,
    role: undefined,
    hand: [],
    bettedAmount: 0,
    card1posX: 370,
    card1posY: 330,
    card2posX: 405,
    card2posY: 330,
  },
];
exports.tableSpots = tableSpots;
